import {  Roboto } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import {  ToastContainer } from 'react-toastify';
import ClientSessionProvider from "./_components/ClientSessionProvider";
import TanstackProvider from "./_components/TansStackProvider";

const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700"] });


import { ThemeProvider } from "./_components/ThemeProvider";
export const metadata = {
  title: "DGHUB",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session, ...pageProps }) {
  
 

  return (
    <html suppressHydrationWarning lang="en">
    <ClientSessionProvider  >
      <TanstackProvider>
      <body className={roboto.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <ToastContainer />
            {children}
          </ThemeProvider>
      </body>
      </TanstackProvider>
    </ClientSessionProvider>
    </html>


  );
}
